use chrono::{DateTime, Local};
use humansize::{SizeFormatter, DECIMAL};
use std::{fs::Permissions, time::SystemTime};

const NOT_AVAILABLE: &str = "N/A";

/// Represents the type of a `PanelItem`, determining the permissible operations for the item.
pub enum FileType {
    Directory,
    Link,
    Parent,
    RegularFile,
    System,
}

/// Represents a file or directory item used to build TUI widgets in the application’s view, displaying file information to the user.
/// It stores metadata about the item: name, type, size, modification date andattributes.
///
/// PanelItem instances are generated by the PanelItemBuilder::build() function.
pub(crate) struct PanelItem {
    name: String,
    ftype: FileType,
    size: String,
    last_modified: String,
    attributes: String,
    selected: bool,
}

impl PanelItem {
    fn new() -> PanelItemBuilder {
        PanelItemBuilder::new()
    }

    /// Returns an instance with data pre-filled for displaying the parent directory item.
    fn parent() -> Self {
        PanelItem {
            name: String::from(".."),
            ftype: FileType::Parent,
            size: String::new(),
            last_modified: String::new(),
            attributes: String::new(),
            selected: false,
        }
    }
}

struct PanelItemBuilder {
    name: String,
    ftype: FileType,
    size: String,
    last_modified: String,
    attributes: String,
    selected: bool,
}

impl PanelItemBuilder {
    fn new() -> Self {
        PanelItemBuilder {
            name: String::new(),
            ftype: FileType::RegularFile,
            size: String::new(),
            last_modified: String::new(),
            attributes: String::new(),
            selected: false,
        }
    }

    fn name<S: AsRef<str>>(mut self, name: S) -> Self {
        self.name = name.as_ref().to_owned();
        self
    }

    fn file_type(mut self, file_type: FileType) -> Self {
        self.ftype = file_type;
        self
    }

    fn size(mut self, size: Option<u64>) -> Self {
        match size {
            Some(fsize) => self.size = format!("{}", SizeFormatter::new(fsize, DECIMAL)),
            // TODO: log error
            None => self.size = String::from(NOT_AVAILABLE),
        }
        self
    }

    fn last_modified(mut self, last_modified: Option<SystemTime>) -> Self {
        self.last_modified = match last_modified {
            Some(modified) => {
                let datetime_local: DateTime<Local> = modified.into();
                let dt_formatted = datetime_local.format("%Y.%m.%d %H:%M");
                dt_formatted.to_string()
            }
            // TODO: log error
            None => String::from(NOT_AVAILABLE),
        };
        self
    }

    fn attributes(mut self, attributes: Option<Permissions>) -> Self {
        self.attributes = match attributes {
            Some(_attrs) => String::from(""),
            None => String::from(NOT_AVAILABLE),
        };
        self
    }

    fn selected(mut self, selected: bool) -> Self {
        self.selected = selected;
        self
    }

    fn build(self) -> PanelItem {
        PanelItem {
            name: self.name,
            ftype: self.ftype,
            size: self.size,
            last_modified: self.last_modified,
            attributes: self.attributes,
            selected: self.selected,
        }
    }
}
