name: Cargo Build & Test

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build and Unit test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        allow_failures: ["beta", "nightly"]
        toolchain:
          - stable
          - beta
          - nightly

    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose
